services:
    Asdoria\SyliusCatalogModePlugin\Validator\Constraints\CatalogModeOrderItemValidator:
        calls:
            - [setCatalogModeChecker, ['@Asdoria\SyliusCatalogModePlugin\Checker\CatalogModeChecker']]
        tags:
            - { name: 'validator.constraint_validator', alias: 'asdoria_catalog_mode_is_enabled' }
